server:
  port: 8081
  servlet:
    context-path: /ems

spring:
  web:
    resources:
      chain:
        strategy:
          content:
            paths: /**
            enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/ems_thymeleaf
    username: root
    password: 123456
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: none
      enabled: true
      schema-locations: classpath:db/migrations/schema.sql
      data-locations: classpath:db/migrations/data.sql
      encoding: utf-8

mybatis:
  configuration:
    map-underscore-to-camel-case: true
