server:
  port: 8081
  servlet:
    context-path: /ems

spring:
  web:
    resources:
      chain:
        strategy:
          content:
            paths: /**
            enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/ems_thymeleaf
    username: root
    password: 123456
    driver-class-name: org.postgresql.Driver

mybatis:
  configuration:
    map-underscore-to-camel-case: true
